// This file is generated by a script. Do not edit manually.
// Exception: `fontFamilyFallback: _thaiFallback` is appended to every style so
// Thai text renders — Ibm and Poppins ship no Thai glyphs. Keep this in the
// generator when regenerating.
import 'package:flutter/widgets.dart';

class AppTypography {
  static const List<String> _thaiFallback = ['NotoSansThai'];

  static const heading1 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 36,
  );
  static const heading2 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 28,
  );
  static const heading3 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 21,
  );
  static const heading4 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 18,
  );
  static const heading5 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 16,
  );
  static const heading6 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 14,
  );
  static const label1 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 16,
  );
  static const label2 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 14,
  );
  static const label3 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 12,
  );
  static const caption1 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 21,
  );
  static const caption2 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 18,
  );
  static const caption3 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 16,
  );
  static const caption4 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 14,
  );
  static const caption5 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 12,
  );
  static const body1 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 16,
  );
  static const body2 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 14,
  );
  static const body3 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 12,
  );
  static const support1 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 10,
  );
  static const support2 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 10,
  );
  static const numericMedium1 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 21,
  );
  static const numericMedium2 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 16,
  );
  static const numericMedium3 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 14,
  );
  static const numericMedium4 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 12,
  );
  static const numericMedium5 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 10,
  );
  static const numericRegular1 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 21,
  );
  static const numericRegular2 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 16,
  );
  static const numericRegular3 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 14,
  );
  static const numericRegular4 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 12,
  );
  static const numericRegular5 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 10,
  );
  static const strikethrough1 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 14,
  );
  static const strikethrough2 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 12,
  );
  static const strikethrough3 = TextStyle(
    fontFamily: 'Poppins',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.normal,
    fontSize: 10,
  );
  static const linkBold1 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 16,
  );
  static const linkBold2 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 14,
  );
  static const linkBold3 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 12,
  );
  static const linkBold4 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.bold,
    fontSize: 10,
  );
  static const linkMedium1 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 16,
  );
  static const linkMedium2 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 14,
  );
  static const linkMedium3 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 12,
  );
  static const linkMedium4 = TextStyle(
    fontFamily: 'Ibm',
    fontFamilyFallback: _thaiFallback,
    fontWeight: FontWeight.w500,
    fontSize: 10,
  );
}
